### ISSUE TITLE
[Question][Android] How to get card number from calypso card / mobib card?

### ISSUE THREAD

**Issue by lorenc-tomasz** [eclipse/keyple-java-example#26]
Hi,
I have Calypso/Mobib card and I would like to get the card number printed on the card. Was playing with the example but without luck. Any suggestions?

**Comment by jeanpierrefortune** [comment]
Hi,

I noticed your query about retrieving the card number from a Calypso/Mobib card. 

To assist you with this, I'd like to point you towards the first Calypso example in the Keyple Java example repository, which demonstrates how to display the serial number. 
You can find this specific example [here](https://github.com/eclipse/keyple-java-example/blob/65ca733d4ab84144bc88c843cca503cd16d6eaae/Example_Card_Calypso/src/main/java/org/eclipse/keyple/card/calypso/example/UseCase1_ExplicitSelectionAid/Main_ExplicitSelectionAid_Pcsc.java#L122).

To successfully run this example and get the card number, please ensure you:
- Set up the plugin and retrieve the PC/SC reader (adjust the reader name if necessary).
- Set the Application Identifier (AID) used for the card selection.
- Run the example with the card already positioned on the reader.

The serial number of the card should be displayed in the console in hexadecimal format. The length of this number is 8 bytes. Keep in mind that sometimes only the 4 least significant bytes are taken into account. Also, be aware that the number printed on the card might be in decimal format, requiring a conversion from hexadecimal if you need to match the printed number.

If you encounter any specific issues or errors while following these steps, please feel free to share them for further assistance.

Hope this helps!

**Comment by lorenc-tomasz** [comment]
Hi @jeanpierrefortune,
thank you for your answer. I have managed to read card number and card serial number. Wondering if it's possible to read calypso cards on iOS? I know that this is Android example, but from technical point of view I'm wondering if iPhones can establish connection with those cards.

**Comment by jeanpierrefortune** [comment]
It is absolutely possible to read a Calypso card with iOS. However, Keyple does not currently address this type of terminal natively.
However, as part of a server-driven operation, it is possible to control card processing by a remote Keyple application using the API for "non-Keyple" client terminals [Server JSON API for non-Keyple clients](https://keyple.org/learn/user-guide/server-json-api/).
In this case, the mobile application developer is left with the task of creating a relatively straightforward application that is responsible almost solely for forwarding the APDUs sent by the server to the card, using the native means provided by the terminal's OS (in this case, the iOS NFC API).

**Comment by jeanpierrefortune** [comment]
Hi @lorenc-tomasz,
It is indeed possible to read a Calypso card using iOS.
However, Keyple currently does not natively support this type of terminal. 
Nevertheless, in a server-driven operation, controlling the card processing via a remote Keyple application is achievable. 
This can be done using a dedicated API as detailed in the [Server JSON API for non-Keyple clients](https://keyple.org/learn/user-guide/server-json-api/). 
In these cases, the mobile application developer simply needs to create a basic application.
This application's primary function is to relay APDUs from the server to the card, utilizing the terminal's native OS capabilities (specifically, the [Apple NFC API](https://developer.apple.com/documentation/corenfc/nfciso7816tag) in this case). 
This approach to handling transactions with a Calypso card is particularly advantageous when implementing the card’s security functions (like certified reading and writing), which require a SAM, because the SAM cannot be physically integrated into an iOS device’s terminal.

**Comment by lorenc-tomasz** [comment]
Hmm.... I have Calypso card with ` Available I/O Class: IsoDep, NfcB` and any of iPhones I have don't see physically the card. 

When I try different cards or tags the delegate method:

```
func tagReaderSession(_ session: NFCTagReaderSession, didDetect tags: [NFCTag]) {
...
```

is fired on iOS. However not when I try to read Calypso card. 

Sorry for bothering you with this, but I'm simply wondering why I cannot even "physically" detect the card on iOS. Tried on iPhone 14, 15, SE 3rd gen and SE 1st gen.

**Comment by jeanpierrefortune** [comment]
I'm not particularly familiar with the iOS NFC API, but I've seen that for ISO7816 tags you need to declare the AIDs of the cards you want to communicate with.
Do you have this configuration?
https://developer.apple.com/documentation/corenfc/nfctagreadersession

**Comment by lorenc-tomasz** [comment]
Hi,
I have all the settings done. I figure it out :D To read the card I need to place it exactly near the antenna. On Android device the NFC module has more power than the one on iPhones.

Thank you for all the answers.
